## Python Numpy Arrays

## Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance
multidimensional array object, and tools for working with these arrays. 
It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## import the library
import numpy as np

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape


(4,)

In [5]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [6]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [7]:
arr1.shape

(3, 5)

In [8]:
#indexing
arr[3]

4

In [9]:
arr[3]=5

In [10]:
arr

array([1, 2, 3, 5])

In [11]:
arr[-1]

5

In [12]:
arr[:-1]

array([1, 2, 3])

In [13]:
arr[::-3]

array([5, 1])

In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
arr1[:,3:].shape

(3, 2)

In [16]:
arr1[:,1]

array([2, 3, 4])

In [17]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [18]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [19]:
##EDA
arr

array([1, 2, 3, 5])

In [20]:
arr[arr<2]

array([1])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [23]:
##mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [24]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [25]:
arr *arr

array([ 1,  4,  9, 25])

In [26]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [27]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.random.randint(10,50,4).reshape(2,2)

array([[22, 46],
       [45, 48]])

In [30]:
np.random.randn(5,6)

array([[ 0.09979269,  0.01603485, -0.07873509, -1.27862604,  1.47812807,
         0.13009016],
       [ 0.97030472,  2.38112471,  1.23268093,  0.69979926,  0.0449191 ,
        -0.947079  ],
       [ 1.51604004,  0.03895761,  0.48292293, -0.54944097, -0.71429093,
        -1.13179741],
       [ 2.21642696,  0.81864775, -1.55105819,  0.04886764, -0.40948152,
         2.25928514],
       [ 0.51996412,  1.15413009,  0.42323398, -0.30536692,  1.85836711,
         0.95042069]])

In [31]:
np.random.random_sample((4,7))

array([[0.00678833, 0.07629317, 0.58125005, 0.51185147, 0.28276411,
        0.85674082, 0.39261311],
       [0.06339276, 0.45073274, 0.6775755 , 0.12724695, 0.49868138,
        0.73322652, 0.32353424],
       [0.16355723, 0.1285335 , 0.25641613, 0.48286246, 0.75906496,
        0.06658562, 0.68529001],
       [0.52318454, 0.44665322, 0.81617913, 0.15739929, 0.99259412,
        0.53742598, 0.34415725]])